ARG ROS_DISTRO
FROM ros:${ROS_DISTRO}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq \
    && apt-get install -y \
        ros-${ROS_DISTRO}-rqt-robot-steering \
    && rm -rf /var/lib/apt/lists/*

CMD ["ros2", "run", "rqt_robot_steering", "rqt_robot_steering"]